steps:
  # RESERVATIONS
  - name: 'gcr.io/cloud-builders/docker' # pre-build container that allows us to build, tag, and push docker images in Gcloud build
    args: [
      'build',
      '-t', # tag
      'us-east4-docker.pkg.dev/tactical-port-393620/reservations/production', # URL to repository
      '-f', 
      'apps/reservations/Dockerfile', # path to Dockerfile
      '.' # path to build context
    ]
  - name: 'gcr.io/cloud-builders/docker' # pre-build container that allows us to build, tag, and push docker images in Gcloud build
    args: ['push', 'us-east4-docker.pkg.dev/tactical-port-393620/reservations/production'] # URL to repository
  
  # AUTH
  - name: 'gcr.io/cloud-builders/docker' # pre-build container that allows us to build, tag, and push docker images in Gcloud build
    args: [
      'build',
      '-t', # tag
      'us-east4-docker.pkg.dev/tactical-port-393620/auth/production', # URL to repository
      '-f', 
      'apps/auth/Dockerfile', # path to Dockerfile
      '.' # path to build context
    ]
  - name: 'gcr.io/cloud-builders/docker' # pre-build container that allows us to build, tag, and push docker images in Gcloud build
    args: ['push', 'us-east4-docker.pkg.dev/tactical-port-393620/auth/production'] # URL to repository
  
  # PAYMENTS
  - name: 'gcr.io/cloud-builders/docker' # pre-build container that allows us to build, tag, and push docker images in Gcloud build
    args: [
      'build',
      '-t', # tag
      'us-east4-docker.pkg.dev/tactical-port-393620/payments/production', # URL to repository
      '-f', 
      'apps/payments/Dockerfile', # path to Dockerfile
      '.' # path to build context
    ]
  - name: 'gcr.io/cloud-builders/docker' # pre-build container that allows us to build, tag, and push docker images in Gcloud build
    args: ['push', 'us-east4-docker.pkg.dev/tactical-port-393620/payments/production'] # URL to repository
  
  # NOTIFICATIONS
  - name: 'gcr.io/cloud-builders/docker' # pre-build container that allows us to build, tag, and push docker images in Gcloud build
    args: [
      'build',
      '-t', # tag
      'us-east4-docker.pkg.dev/tactical-port-393620/notifications/production', # URL to repository
      '-f', 
      'apps/notifications/Dockerfile', # path to Dockerfile
      '.' # path to build context
    ]
  - name: 'gcr.io/cloud-builders/docker' # pre-build container that allows us to build, tag, and push docker images in Gcloud build
    args: ['push', 'us-east4-docker.pkg.dev/tactical-port-393620/notifications/production'] # URL to repository